name: firstTestWorkflow
on:
  push:
    branches:
      - main
jobs: 
  buildJob:
    runs-on: ubuntu-latest
    steps:
      - name: checkoutCode
        uses: actions/checkout@v4

      - name: setup Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Dependencies
        run: npm install
